name: Build and Deploy
on:
  push:
    branches: website

jobs:
  build-and-deploy:
    name: Build and deploy Gatsby site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.5.0

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install Project Dependencies
        run: yarn

      - name: Build
        run: yarn build

      - name: Copy files
        uses: canastro/copy-file-action@master
        with:
          source: "public/**"
          target: "docs/"